---

# Task file that install and configure s3cmd on RHEL Debian/Ubuntu Family

- name: Install s3cmd dependencies
  package:
    name:
      - python3
      - python3-pip
    state: present

- name: Install s3cmd package via pip
  pip:
    executable: pip3
    name: s3cmd
    state: present
