---

# Task file that install and configure s3cmd

- name: Install s3cmd on RHEL Family
  include_tasks: install_rhel.yml
  when: ansible_os_family == "RedHat"

- name: Install s3cmd on Debian Family
  include_tasks: install_debian.yml
  when: ansible_os_family == "Debian"

- name: Put configuration into '{{ s3cmd_user }}' home dir
  include_tasks: config_user.yml

- name: Create a $S3 environment variable for all users
  become: true
  template:
    src: templates/s3.sh.j2
    dest: /etc/profile.d/s3.sh
  when: s3_global_env_var
